# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0fccef71f1dad975807ea079052417bf61499bad1fdce72550a96d76f751adc87412c272d298c1952b9c833870312ddcb7bf9b530def60052e6bfb30f14910

test:
  secret_key_base: aaac18ee05cba3ff19de0c9e656264d994ca8c7b60233cba41d9bc3ab8f246d4d75cfdd29a79ad7ef03e89b06aed76caeac9d43211f0b99be36c892ec8c28797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
